ARG BASE_IMAGE=nvcr.io/nvidia/deepstream:6.1-triton
FROM ${BASE_IMAGE}

# Install JupyterLab and settings
RUN apt update \
    && apt install -y python3-pip
RUN pip3 install jupyterlab


RUN apt-get update && \
    apt-get install -y \
	git \
	python \
	vim \
	ffmpeg

RUN rm -rf /var/lib/apt/lists/* && \
	apt autoremove -y


RUN wget https://github.com/NVIDIA-AI-IOT/deepstream_python_apps/releases/download/v1.1.3/pyds-1.1.3-py3-none-linux_x86_64.whl
RUN pip3 install pyds-1.1.3-py3-none-linux_x86_64.whl

RUN cd /opt/nvidia/deepstream/deepstream-6.1/sources && \
    git clone https://github.com/NVIDIA-AI-IOT/deepstream_python_apps

# Jupyter listens on 8888.
EXPOSE 8888

# set jupyter auto-start command
ENTRYPOINT ["/bin/bash"]
